services:
  - type: web
    name: olist-dashboard
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app_render:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DASH_DEBUG_MODE
        value: False
        